services:
#  rabbitmq:
#    image: rabbitmq:latest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: your_username
#      RABBITMQ_DEFAULT_PASS: your_password

#  api:
#    build:
#      context: ./API
#      dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    environment:
#      ASPNETCORE_ENVIRONMENT: Production
  
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8080:5254"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  followersservice:
    build:
      context: ./FollowersService
      dockerfile: Dockerfile
    ports:
      - "8081:5256"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  likeservice:
    build:
      context: ./LikeService
      dockerfile: Dockerfile
    ports:
      - "8082:5257"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "8083:5258"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  postservice:
    build:
      context: ./PostService
      dockerfile: Dockerfile
    ports:
      - "8084:5259"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  searchservice:
    build:
      context: ./SearchService
      dockerfile: Dockerfile
    ports:
      - "8085:5260"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8086:5261"
    environment:
      ASPNETCORE_ENVIRONMENT: Production