version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
        - "5672:5672"
        - "15672:15672"

  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  auth-service:
    image: auth-service
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "81:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      rabbitmq:
        condition: service_healthy

  #followers-service:
  #  image: followers-service
  #  build:
  #    context: .
  #    dockerfile: FollowersService/Dockerfile
  #  ports:
  #    - "82:80"
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Production
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy

  #like-service:
  #  image: like-service
  #  build:
  #    context: .
  #    dockerfile: LikeService/Dockerfile
  #  ports:
  #    - "83:80"
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Production
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
#
  #notification-service:
  #  image: notification-service
  #  build:
  #    context: .
  #    dockerfile: NotificationService/Dockerfile
  #  ports:
  #    - "84:80"
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Production
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #      
  #post-service:
  #  image: post-service
  #  build:
  #    context: .
  #    dockerfile: PostService/Dockerfile
  #  ports:
  #    - "85:80"
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Production
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
#
  #search-service:
  #  image: search-service
  #  build:
  #    context: .
  #    dockerfile: SearchService/Dockerfile
  #  ports:
  #    - "86:80"
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Production
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #
  #user-service:
  #  image: user-service
  #  build:
  #    context: .
  #    dockerfile: UserService/Dockerfile
  #  ports:
  #    - "87:80"
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Production
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy